version: "3"
services:
  postgres:
    image: "postgres:latest"
    container_name: "fib-docker-postgres"

  redis:
    image: "redis:latest"
    container_name: "fib-docker-redis"

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - redis
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: fib-client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # enables hot-reloadin with WebPack

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  nginx:
    restart: always
    build:
     context: ./nginx
     dockerfile: Dockerfile.dev
    ports:
      - "3001:80"
    depends_on:
      - api
      - client



